name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - ruby-workflows-poc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 2.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
